package theme

import (
	"fmt"
	"strings"
)

func GeneratePlymouth(name string) (string, error) {
	if name == "" {
		return "", fmt.Errorf("theme name empty")
	}
	b := &strings.Builder{}
	fmt.Fprintf(b, "[Plymouth Theme]\n")
	fmt.Fprintf(b, "Name=%s\n", name)
	fmt.Fprintf(b, "Description=Generated by ptc\n")
	fmt.Fprintf(b, "ModuleName=script\n")
	fmt.Fprintf(b, "ImageDir=assets\n")
	fmt.Fprintf(b, "ScriptFile=%s.script\n", name)
	return b.String(), nil
}

func ValidatePlymouth(content string) error {
	required := []string{
		"[Plymouth Theme]",
		"Name=",
		"ModuleName=script",
		"ImageDir=assets",
		"ScriptFile=",
	}
	for _, key := range required {
		if !strings.Contains(content, key) {
			return fmt.Errorf("missing required: %s", key)
		}
	}
	return nil
}
