package theme

import (
	"fmt"
	"path/filepath"
	"strings"
	"text/template"

	"github.com/dan/plymouth-theme-creator/internal/script"
)

type ScriptOpts struct {
	Name       string
	Frames     []string
	Loop       bool
	Transition string
}

var scriptTmpl = template.Must(template.New("script").Parse(`// {{.Name}}.script — generated by ptc
var frames = [
{{- range .Frames}}
    new Image("{{.}}"),
{{- end }}
];

var frameIdx = 0;

Plymouth.SetRefreshFunction(function () {
    var img = frames[frameIdx];
    img.SetPosition(
        Window.GetWidth() / 2 - img.GetWidth() / 2,
        Window.GetHeight() / 2 - img.GetHeight() / 2
    );
    img.Draw();
{{- if .Loop }}
    frameIdx = (frameIdx + 1) % frames.length;
{{- else }}
    if (frameIdx < frames.length - 1) {
        frameIdx++;
    }
{{- end }}
});
`))

func GenerateScript(opts ScriptOpts) (string, error) {
	if len(opts.Frames) == 0 {
		return "", fmt.Errorf("no frames")
	}
	var b strings.Builder
	if err := scriptTmpl.Execute(&b, opts); err != nil {
		return "", err
	}
	return b.String(), nil
}

// ValidateScript checks asset refs and V4 token whitelist.
func ValidateScript(content string, assets []string) error {
	if err := script.Validate(content); err != nil {
		return err
	}

	// V5: every Image("...") basename must exist in assets.
	for _, line := range strings.Split(content, "\n") {
		idx := strings.Index(line, `new Image("`)
		if idx == -1 {
			continue
		}
		start := idx + len(`new Image("`)
		end := strings.Index(line[start:], `"`)
		if end == -1 {
			continue
		}
		ref := line[start : start+end]
		base := filepath.Base(ref)
		found := false
		for _, a := range assets {
			if filepath.Base(a) == base {
				found = true
				break
			}
		}
		if !found {
			return fmt.Errorf("asset ref not found: %s", ref)
		}
	}
	return nil
}
